name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-main:
    name: build-main
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SFML
      run: sudo apt-get install libsfml-dev 
    - name: make
      run: |
         cd Code/
         make
  build-and-run-tests:
    name: build-and-run-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SFML
      run: sudo apt-get install libsfml-dev 
    - name: make
      run: |
         cd Tests/
         make
         ./tests
